# makefile for make-based platforms

ALL_TARGETS =  face$(E) face2$(E) face3$(E)

!include ..\environ

LDLIBS_HOOK =

faceOBJS = face$(O)

LDLIBS_HOOK =

face2OBJS = face2$(O)

LDLIBS_HOOK =

face3OBJS = face3$(O)

