#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:43:05 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME =	../../..

SOURCES =	\
		gs_ui.cc

COMPONENT = GS_UI

LIBNAME =	lib$(COMPONENT).a

include		${SOURCE_HOME}/make/leaf.mk

