# makefile for make-based platforms

ALL_TARGETS =  filechs1$(E) filechs2$(E) filechs3$(E)

!include ..\environ

LDLIBS_HOOK =

filechs1OBJS = filechs1$(O)

LDLIBS_HOOK =

filechs2OBJS = filechs2$(O)

LDLIBS_HOOK =

filechs3OBJS = filechs3$(O)

