/* $Id: vhdrdefs.h,v 1.171 1997/10/14 19:12:59 robert Exp $ */

#ifndef vhdrdefsINCLUDED
#define vhdrdefsINCLUDED 1

#ifndef  vhdrmodeINCLUDED
#include <vhdrmode.h>
#endif

#if (vhdrmodeSHORT_NAMES)

#define vabstractHEADER                         <vabstrac.h>
#define vacceptHEADER                           <vaccept.h>
#define vaccept_cHEADER                         <vaccep_c.h>
#define vappframeHEADER                         <vappfram.h>
#define vappframe_cHEADER                       <vappfr_c.h>
#define vapplicationHEADER                      <vapplica.h>
#define vapplication_cHEADER                    <vappli_c.h>
#define vargscrapHEADER                         <vargscra.h>
#define varpainetHEADER                         <varpaine.h>
#define varrayHEADER                            <varray.h>
#define vassertHEADER                           <vassert.h>
#define vatHEADER                               <vat.h>
#define vattributeHEADER                        <vattribu.h>
#define vattribute_cHEADER                      <vattri_c.h>
#define vblockHEADER                            <vblock.h>
#define vboolitemHEADER                         <vboolite.h>
#define vboolitem_cHEADER                       <vbooli_c.h>
#define vbtreeHEADER                            <vbtree.h>
#define vbtree_cHEADER                          <vbtree_c.h>
#define vbufferHEADER                           <vbuffer.h>
#define vbuffer_cHEADER                         <vbuffe_c.h>
#define vbuildNumberHEADER                      <vbldnum.h>
#define vbuildstrsHEADER                        <vbuildst.h>
#define vbuildstrsSOURCE                        <vbuildst.c>
#define vbuttonHEADER                           <vbutton.h>
#define vbutton_cHEADER                         <vbutto_c.h>
#define vcanvasHEADER                           <vcanvas.h>
#define vcanvas_cHEADER                         <vcanva_c.h>
#define vcharHEADER                             <vchar.h>
#define vchar_cHEADER                           <vchar_c.h>
#define vcharencodingHEADER                     <vcharenc.h>
#define vcharencoding_cHEADER                   <vchare_c.h>
#define vchunkHEADER                            <vchunk.h>
#define vclassHEADER                            <vclass.h>
#define vclass_cHEADER                          <vclass_c.h>
#define vclassextraHEADER                       <vclassex.h>
#define vclassinfoHEADER                        <vclassin.h>
#define vclassregHEADER                         <vclassre.h>
#define vclexHEADER                             <vclex.h>
#define vclientHEADER                           <vclient.h>
#define vclient_cHEADER                         <vclien_c.h>
#define vclipboardHEADER                        <vclipboa.h>
#define vclipboard_cHEADER                      <vclipb_c.h>
#define vcmdchsrHEADER                          <vcmdchsr.h>
#define vcmdchsr_cHEADER                        <vcmdch_c.h>
#define vcolorHEADER                            <vcolor.h>
#define vcolor_cHEADER                          <vcolor_c.h>
#define vcolorchsrHEADER                        <vcolorch.h>
#define vcolorchsr_cHEADER                      <vcolch_c.h>
#define vcolorsysHEADER                         <vcolorsy.h>
#define vcomboHEADER                            <vcombo.h>
#define vcombo_cHEADER                          <vcombo_c.h>
#define vcomboboxHEADER                         <vcombobo.h>
#define vcombobox_cHEADER                       <vcombx_c.h>
#define vcommChannelHEADER                      <vcommchn.h>
#define vcommChannel_cHEADER                    <vcommc_c.h>
#define vcommHEADER                             <vcomm.h>
#define vcomm_cHEADER                           <vcomm_c.h>
#define vcommandHEADER                          <vcommand.h>
#define vcommand_cHEADER                        <vcomma_c.h>
#define vcommdllHEADER                          <vcommdll.h>
#define vcommfixHEADER                          <vcommfix.h>
#define vconditionHEADER                        <vconditi.h>
#define vconfirmHEADER                          <vconfirm.h>
#define vconfirm_cHEADER                        <vconfi_c.h>
#define vcontainerGridHEADER                    <vctrgrid.h>
#define vcontainerGrid_cHEADER                  <vctrgr_c.h>
#define vcontainerHEADER                        <vcontain.h>
#define vcontainer_cHEADER                      <vconta_c.h>
#define vcontrolHEADER                          <vcontrol.h>
#define vcontrol_cHEADER                        <vcontr_c.h>
#define vctlchsrHEADER                          <vctlchsr.h>
#define vctlchsr_cHEADER                        <vctlch_c.h>
#define vctypeHEADER                            <vctype.h>
#define vcursorHEADER                           <vcursor.h>
#define vcursor_cHEADER                         <vcurso_c.h>
#define vdasdictHEADER                          <vdasdict.h>
#define vdasservHEADER                          <vdasserv.h>
#define vdasserv_cHEADER                        <vdasse_c.h>
#define vdatasourceChooserHEADER                <vdschsr.h>
#define vdatasourceChooser_cHEADER              <vdschs_c.h>
#define vdatasourceDataHEADER                   <vdsdata.h>
#define vdatasourceData_cHEADER                 <vdsdat_c.h>
#define vdatasourceDatabaseEngineHEADER         <vdsdbeng.h>
#define vdatasourceDatabaseEngine_cHEADER       <vdsdbe_c.h>
#define vdatasourceFileSysEngineHEADER          <vdsfseng.h>
#define vdatasourceFileSysEngine_cHEADER        <vdsfse_c.h>
#define vdatasourceHEADER                       <vdatasou.h>
#define vdatasourceUserInterfaceEngineHEADER    <vdsuieng.h>
#define vdatasourceUserInterfaceEngine_cHEADER  <vdsuie_c.h>
#define vdatasource_cHEADER                     <vdatas_c.h>
#define vdatatagHEADER                          <vdatatag.h>
#define vdatatag_cHEADER                        <vdatat_c.h>
#define vdateHEADER                             <vdate.h>
#define vdate_cHEADER                           <vdate_c.h>
#define vdateitemHEADER                         <vdateite.h>
#define vdateitem_cHEADER                       <vdatei_c.h>
#define vdbHEADER                               <vdb.h>
#define vdbServiceHEADER                        <vdbserv.h>
#define vdb_cHEADER                             <vdb_c.h>
#define vdbchsrHEADER                           <vdbchsr.h>
#define vdbchsr_cHEADER                         <vdbchs_c.h>
#define vdbcomboboxHEADER                       <vdbcombo.h>
#define vdbformHEADER                           <vdbform.h>
#define vdblistHEADER                           <vdblist.h>
#define vdbmenuHEADER                           <vdbmenu.h>
#define vdbprivHEADER                           <vdbpriv.h>
#define vdbqueryHEADER                          <vdbquery.h>
#define vdbquerybuilderHEADER                   <vdbqb.h>
#define vdbspecHEADER                           <vdbspec.h>
#define vdbspinnerHEADER                        <vdbspinn.h>
#define vdebugHEADER                            <vdebug.h>
#define vdebug_cHEADER                          <vdebug_c.h>
#define vdebugutHEADER                          <vdebugut.h>
#define vdelegatorHEADER                        <vdelegat.h>
#define vdelegator_cHEADER                      <vdeleg_c.h>
#define vdialogHEADER                           <vdialog.h>
#define vdialogItemHEADER                       <vdialog.h>
#define vdialog_cHEADER                         <vdialo_c.h>
#define vdialogsysHEADER                        <vdialsys.h>
#define vdictHEADER                             <vdict.h>
#define vdict_cHEADER                           <vdict_c.h>
#define vdirentHEADER                           <vdirent.h>
#define vdockHEADER                             <vdock.h>
#define vdock_cHEADER                           <vdock_c.h>
#define vdockcontainerHEADER                    <vdockcnt.h>
#define vdockcontainer_cHEADER                  <vdockc_c.h>
#define vdockerHEADER                           <vdocker.h>
#define vdocker_cHEADER                         <vdocke_c.h>
#define vdockitemHEADER                         <vdockitm.h>
#define vdockitem_cHEADER                       <vdocki_c.h>
#define vdomainHEADER                           <vdomain.h>
#define vdomain_cHEADER                         <vdomai_c.h>
#define vdomainitemHEADER                       <vdomitem.h>
#define vdomainitem_cHEADER                     <vdomit_c.h>
#define vdomainviewHEADER                       <vdomview.h>
#define vdomainview_cHEADER                     <vdomvi_c.h>
#define vdoubleHEADER                           <vdouble.h>
#define vdoubleitemHEADER                       <vdblitem.h>
#define vdoubleitem_cHEADER                     <vdblit_c.h>
#define vdragHEADER                             <vdrag.h>
#define vdrag_cHEADER                           <vdrag_c.h>
#define vdrawHEADER                             <vdraw.h>
#define vdraw_cHEADER                           <vdraw_c.h>
#define vdrawcontextHEADER                      <vdrawcon.h>
#define vdrawcontext_cHEADER                    <vdrwco_c.h>
#define vdrawpathHEADER                         <vdrawpat.h>
#define vdrawpath_cHEADER                       <vdrwpa_c.h>
#define vdrawpenHEADER                          <vdrawpen.h>
#define vdrawpen_cHEADER                        <vdrwpe_c.h>
#define vdrawrectsetHEADER                      <vdrawrec.h>
#define vdrawrectset_cHEADER                    <vdrwre_c.h>
#define vdrawsysHEADER                          <vdrawsys.h>
#define vdropHEADER                             <vdropsit.h> /* !!! remove */
#define vdrop_cHEADER                           <vdrops_c.h> /* !!! remove */
#define vdropsiteHEADER                         <vdropsit.h>
#define vdropsite_cHEADER                       <vdrops_c.h>
#define vdsdbeng_cHEADER                        <vdsdbe_c.h>
#define vdsfseng_cHEADER                        <vdsfse_c.h>
#define vdsuieng_cHEADER                        <vdsuie_c.h>
#define verrnoHEADER                            <verrno.h>
#define vevent2HEADER                           <vevent2.h>
#define vevent2_cHEADER                         <veven2_c.h>
#define vevent2sysHEADER                        <vevent2s.h>
#define vevent2sys_cHEADER                      <vevn2s_c.h>
#define veventHEADER                            <vevent.h>
#define vevent_cHEADER                          <vevent_c.h>
#define veventsysHEADER                         <veventsy.h>
#define veventsys_cHEADER                       <vevnsy_c.h>
#define vevntitrHEADER                          <vevntitr.h>
#define vevntitr_cHEADER                        <vevnti_c.h>
#define vexHEADER                               <vex.h>
#define vex_cHEADER                             <vex_c.h>
#define vexportHEADER                           <vexport.h>
#define vexsysHEADER                            <vexsys.h>
#define vfcntlHEADER                            <vfcntl.h>
#define vfieldHEADER                            <vfield.h>
#define vfield_cHEADER                          <vfield_c.h>
#define vfileHEADER                             <vfile.h>
#define vfile_cHEADER                           <vfile_c.h>
#define vfilechsrHEADER                         <vfilechs.h>
#define vfilechsr_cHEADER                       <vfilec_c.h>
#define vfixedHEADER                            <vfixed.h>
#define vfixed_cHEADER                          <vfixed_c.h>
#define vfloatHEADER                            <vfloat.h>
#define vfontHEADER                             <vfont.h>
#define vfont_cHEADER                           <vfont_c.h>
#define vfontchsrHEADER                         <vfontchs.h>
#define vfontchsr_cHEADER                       <vfontc_c.h>
#define vfontspecHEADER                         <vfontspe.h>
#define vfontspec_cHEADER                       <vfonts_c.h>
#define vfontsysHEADER                          <vfontsys.h>
#define vformContextHEADER                      <vfrmctxt.h>
#define vformContext_cHEADER                    <vfrmct_c.h>
#define vformHEADER                             <vform.h>
#define vform_cHEADER                           <vform_c.h>
#define vformatHEADER                           <vformat.h>
#define vformat_cHEADER                         <vforma_c.h>
#define vfsHEADER                               <vfs.h>
#define vfs_cHEADER                             <vfs_c.h>
#define vgalaxyBuildNumberHEADER                <vgalbnum.h>
#define vgalaxyHEADER                           <vgalaxy.h>
#define vglitemHEADER                           <vglitem.h>
#define vglwinHEADER                            <vglwin.h>
#define vgraphHEADER                            <vgraph.h>
#define vgridcontainerHEADER                    <vgridcon.h>
#define vgridcontainer_cHEADER                  <vgridc_c.h>
#define vgridmodelHEADER                        <vgridmod.h>
#define vgridmodel_cHEADER                      <vgridm_c.h>
#define vgrpHEADER                              <vgrp.h>
#define vhdrdefsHEADER                          <vhdrdefs.h>
#define vhdrmodeHEADER                          <vhdrmode.h>
#define vhelpHEADER                             <vhelp.h>
#define vhelpRunnableHEADER                     <vhelprun.h>
#define vhelp_cHEADER                           <vhelp_c.h>
#define vhelpdasHEADER                          <vhelpdas.h>
#define vhelpdisplayHEADER                      <vhelpdis.h>
#define vhelpdisplay_cHEADER                    <vhpdis_c.h>
#define vhelpdocHEADER                          <vhelpdoc.h>
#define vhelpdefaultHEADER                      <vhelpdef.h>
#define vhelpdefault_cHEADER                    <vhpdef_c.h>
#define vhelpexplorerHEADER                     <vhelpexp.h>
#define vhelpexplorer_cHEADER                   <vhpexp_c.h>
#define vhelpgalaxyHEADER                       <vhelpgal.h>
#define vhelpgalaxy_cHEADER                     <vhpgal_c.h>
#define vhelphtmlgalaxyHEADER                   <vhelphtg.h>
#define vhelphtmlgalaxy_cHEADER                 <vhphtg_c.h>
#define vhelphtmllocatorHEADER                  <vhelphtl.h>
#define vhelphtmllocator_cHEADER                <vhphtl_c.h>
#define vhelphypertextHEADER                    <vhelphyp.h>
#define vhelphypertext_cHEADER                  <vhphyp_c.h>
#define vhelplinkerHEADER                       <vhelplin.h>
#define vhelplocatorHEADER                      <vhelploc.h>
#define vhelplocator_cHEADER                    <vhploc_c.h>
#define vhelpnetscapeHEADER                     <vhelpnet.h>
#define vhelpnetscape_cHEADER                   <vhpnet_c.h>
#define vhelpobjectHEADER                       <vhelpobj.h>
#define vhelpobject_cHEADER                     <vhpobj_c.h>
#define vhelprefHEADER                          <vhelpref.h>
#define vhelpref_cHEADER                        <vhpref_c.h>
#define vhelpreflocatorHEADER                   <vhelprfl.h>
#define vhelpreflocator_cHEADER                 <vhprfl_c.h>
#define vhelpregistryHEADER                     <vhelpreg.h>
#define vhelpregistry_cHEADER                   <vhpreg_c.h>
#define vhelprequestHEADER                      <vhelpreq.h>
#define vhelprequest_cHEADER                    <vhpreq_c.h>
#define vhelpstatusHEADER                       <vhelpsta.h>
#define vhelpstatus_cHEADER                     <vhpsta_c.h>
#define vhelptextHEADER                         <vhelptex.h>
#define vhelptext_cHEADER                       <vhptex_c.h>
#define vhelptextlocatorHEADER                  <vhelptxl.h>
#define vhelptextlocator_cHEADER                <vhptxl_c.h>
#define vhelptooltipHEADER                      <vhelptip.h>
#define vhelptooltip_cHEADER                    <vhptip_c.h>
#define vhelptransHEADER                        <vhelptra.h>
#define vhelpwinhelpHEADER                      <vhelpwin.h>
#define vhelpwinhelp_cHEADER                    <vhpwin_c.h>
#define vhexHEADER                              <vhex.h>
#define vhex_cHEADER                            <vhex_c.h>
#define vhexchsrHEADER                          <vhexchsr.h>
#define vhexchsr_cHEADER                        <vhexch_c.h>
#define vhtmlHEADER                             <vhtml.h>
#define vhtmledHEADER                           <vhtmled.h>
#define vi18nHEADER                             <vi18n.h>
#define viconviewHEADER                         <viconvie.h>
#define viconview_cHEADER                       <viconv_c.h>
#define vimageHEADER                            <vimage.h>
#define vimage_cHEADER                          <vimage_c.h>
#define vimageedtrHEADER                        <vimageed.h>
#define vimageedtr_cHEADER                      <vimagd_c.h>
#define vimgedHEADER                            <vimged.h>
#define vimgedutilsHEADER                       <vimgedut.h>
#define vimgutilsHEADER                         <vimgutil.h>
#define vimportHEADER                           <vimport.h>
#define vinputHEADER                            <vinput.h>
#define vinput_cHEADER                          <vinput_c.h>
#define vinputsysHEADER                         <vinputsy.h>
#define vinstHEADER                             <vinst.h>
#define vinst_cHEADER                           <vinst_c.h>
#define vinstallHEADER                          <vinstall.h>
#define vinstall_cHEADER                        <vinstl_c.h>
#define vinstanceHEADER                         <vinstanc.h>
#define vinstance_cHEADER                       <vinsta_c.h>
#define vinterfaceHEADER                        <vinterfa.h>
#define vinterface_cHEADER                      <vinter_c.h>
#define vioHEADER                               <vio.h>
#define viteratorHEADER                         <viterato.h>
#define viterator_cHEADER                       <vitera_c.h>
#define vkeyHEADER                              <vkey.h>
#define vkey_cHEADER                            <vkey_c.h>
#define vkeyitemHEADER                          <vkeyitem.h>
#define vkeyitem_cHEADER                        <vkeyit_c.h>
#define vkeysysHEADER                           <vkeysys.h>
#define vkindHEADER                             <vkind.h>
#define vlafHEADER                              <vlaf.h>
#define vlaf_cHEADER                            <vlaf_c.h>
#define vlibcHEADER                             <vlibc.h>
#define vlimitsHEADER                           <vlimits.h>
#define vlistHEADER                             <vlist.h>
#define vlist_cHEADER                           <vlist_c.h>
#define vlisteditHEADER                         <vlistedi.h>
#define vlistitemHEADER                         <vlistite.h>
#define vlistitem_cHEADER                       <vlisti_c.h>
#define vlistselectionHEADER                    <vlistsel.h>
#define vlistselection_cHEADER                  <vlistn_c.h>
#define vlistsizeHEADER                         <vlistsiz.h>
#define vlistsize_cHEADER                       <vlistz_c.h>
#define vliststrHEADER                          <vliststr.h>
#define vliststr_cHEADER                        <vlists_c.h>
#define vlistviewHEADER                         <vlistvie.h>
#define vlistview_cHEADER                       <vlistv_c.h>
#define vloadableHEADER                         <vloadabl.h>
#define vloadable_cHEADER                       <vloada_c.h>
#define vlocaleHEADER                           <vlocale.h>
#define vlockHEADER                             <vlock.h>
#define vlongitemHEADER                         <vlongite.h>
#define vlongitem_cHEADER                       <vlongi_c.h>
#define vlonglongHEADER                         <vlonglon.h>
#define vlonglong_cHEADER                       <vlongl_c.h>
#define vmaccontrolsHEADER                      <vmaccont.h>
#define vmacdialogsHEADER                       <vmacdial.h>
#define vmacerrorsHEADER                        <vmacerro.h>
#define vmaceventsHEADER                        <vmaceven.h>
#define vmacfilesHEADER                         <vmacfile.h>
#define vmacfontsHEADER                         <vmacfont.h>
#define vmacgestaltequHEADER                    <vmacgest.h>
#define vmachineHEADER                          <vmachine.h>
#define vmachine_cHEADER                        <vmachi_c.h>
#define vmacmemoryHEADER                        <vmacmemo.h>
#define vmacquickdrawHEADER                     <vmacquic.h>
#define vmacresourcesHEADER                     <vmacreso.h>
#define vmacscriptHEADER                        <vmacscri.h>
#define vmacstringsHEADER                       <vmacstri.h>
#define vmacsysequHEADER                        <vmacsyse.h>
#define vmactypesHEADER                         <vmactype.h>
#define vmacwindowsHEADER                       <vmacwind.h>
#define vmaindialogHEADER                       <vmaindia.h>
#define vmainviewHEADER                         <vmainvie.h>
#define vmainview_cHEADER                       <vmainv_c.h>
#define vmappingHEADER                          <vmapping.h>
#define vmapping_cHEADER                        <vmappi_c.h>
#define vmaskitemHEADER                         <vmaskite.h>
#define vmaskitem_cHEADER                       <vmaski_c.h>
#define vmathHEADER                             <vmath.h>
#define vmatrixHEADER                           <vmatrix.h>
#define vmatrix_cHEADER                         <vmatri_c.h>
#define vmemHEADER                              <vmem.h>
#define vmem_cHEADER                            <vmem_c.h>
#define vmemsysHEADER                           <vmemsys.h>
#define vmenuHEADER                             <vmenu.h>
#define vmenu_cHEADER                           <vmenu_c.h>
#define vmenubarHEADER                          <vmenubar.h>
#define vmenubar_cHEADER                        <vmenub_c.h>
#define vmessageHEADER                          <vmessage.h>
#define vmoduleHEADER                           <vmodule.h>
#define vmodule_cHEADER                         <vmodul_c.h>
#define vmswhdrsHEADER                          <vmswhdrs.h>
#define vmutexHEADER                            <vmutex.h>
#define vmutexsysHEADER                         <vmutexsy.h>
#define vnameHEADER                             <vname.h>
#define vname_cHEADER                           <vname_c.h>
#define vnameobjectHEADER                       <vnameobj.h>
#define vnameobject_cHEADER                     <vnameo_c.h>
#define vndxHEADER                              <vndx.h>
#define vnetdbHEADER                            <vnetdb.h>
#define vnetinetinHEADER                        <vnetinet.h>
#define vnotebookHEADER                         <vnoteboo.h>
#define vnotebook_cHEADER                       <vnoteb_c.h>
#define vnoticeHEADER                           <vnotice.h>
#define vnotice_cHEADER                         <vnotic_c.h>
#define vnumHEADER                              <vnum.h>
#define vnum_cHEADER                            <vnum_c.h>
#define vobjectHEADER                           <vobject.h>
#define vobject_cHEADER                         <vobjec_c.h>
#define vobservableHEADER                       <vobserva.h>
#define vobservable_cHEADER                     <vobsab_c.h>
#define vobserverHEADER                         <vobserve.h>
#define vobserver_cHEADER                       <vobser_c.h>
#define voccurrenceHEADER                       <voccurre.h>
#define voccurrence_cHEADER                     <voccur_c.h>
#define vodbcHEADER                             <vodbc.h>
#define voleHEADER                              <vole.h>
#define vole_cHEADER                            <vole_c.h>
#define volectrlHEADER                          <volectrl.h>
#define volectrl_cHEADER                        <volect_c.h>
#define volesiteHEADER                          <volesite.h>
#define volesite_cHEADER                        <volesi_c.h>
#define volevariantHEADER                       <volevari.h>
#define volevariant_cHEADER                     <voleva_c.h>
#define volegenHEADER                           <volegen.h>
#define volegen_cHEADER                         <volege_c.h>
#define vos2HEADER                              <vos2.h>
#define vpaledHEADER                            <vpaled.h>
#define vpaletteHEADER                          <vpalette.h>
#define vpalette_cHEADER                        <vpalet_c.h>
#define vpanecontainerHEADER                    <vpanecon.h>
#define vpanecontainer_cHEADER                  <vpanec_c.h>
#define vpathscrapHEADER                        <vpthscrp.h>
#define vpathscrap_cHEADER                      <vpthsc_c.h>
#define vpersistentHEADER                       <vpersist.h>
#define vpersistent_cHEADER                     <vpersi_c.h>
#define vpixmapHEADER                           <vpixmap.h>
#define vpixmap_cHEADER                         <vpixma_c.h>
#define vpointHEADER                            <vpoint.h>
#define vpoint_cHEADER                          <vpoint_c.h>
#define vpoolHEADER                             <vpool.h>
#define vpool_cHEADER                           <vpool_c.h>
#define vportHEADER                             <vport.h>
#define vportenvHEADER                          <vportenv.h>
#define vportmacHEADER                          <vportmac.h>
#define vpqHEADER                               <vpq.h>
#define vpq_cHEADER                             <vpq_c.h>
#define vprefHEADER                             <vpref.h>
#define vpref_cHEADER                           <vpref_c.h>
#define vprintHEADER                            <vprint.h>
#define vprint_cHEADER                          <vprint_c.h>
#define vprintsysHEADER                         <vprintsy.h>
#define vprocessHEADER                          <vprocess.h>
#define vprocess_cHEADER                        <vproce_c.h>
#define vpscontextHEADER                        <vpsconte.h>
#define vpsdictHEADER                           <vpsdict.h>
#define vpserrorHEADER                          <vpserror.h>
#define vpsfileHEADER                           <vpsfile.h>
#define vpsinterpHEADER                         <vpsinter.h>
#define vpsobjectHEADER                         <vpsobjec.h>
#define vpsopHEADER                             <vpsop.h>
#define vpsscanHEADER                           <vpsscan.h>
#define vpsstackHEADER                          <vpsstack.h>
#define vpsvmHEADER                             <vpsvm.h>
#define vpwdHEADER                              <vpwd.h>
#define vpwditemHEADER                          <vpwditem.h>
#define vpwditem_cHEADER                        <vpwdit_c.h>
#define vqueryHEADER                            <vquery.h>
#define vqueryvalueHEADER                       <vqueryva.h>
#define vquerybuilderHEADER                     <vquerybu.h>
#define vreHEADER                               <vre.h>
#define vreaderHEADER                           <vreader.h>
#define vrectHEADER                             <vrect.h>
#define vrect_cHEADER                           <vrect_c.h>
#define vredeclHEADER                           <vredecl.h>
#define vreeditorHEADER                         <vreedito.h>
#define vrefileHEADER                           <vrefile.h>
#define vregexpHEADER                           <vregexp.h>
#define vregexp_cHEADER                         <vregex_c.h>
#define vreinitHEADER                           <vreinit.h>
#define vrepanelHEADER                          <vrepanel.h>
#define vreplabel_cHEADER                       <vreplb_c.h>
#define vreplangHEADER                          <vreplang.h>
#define vreplang_cHEADER                        <vrepla_c.h>
#define vreportComponentHEADER                  <vreportc.h>
#define vreportComponent_cHEADER                <vrptcm_c.h>
#define vreportDataChooserHEADER                <vrdchsr.h>
#define vreportDataChooser_cHEADER              <vrdchs_c.h>
#define vreportDeviceChooserHEADER              <vrdevchs.h>
#define vreportDeviceChooser_cHEADER            <vrdevc_c.h>
#define vreportDeviceHEADER                     <vreportd.h>
#define vreportDevice_cHEADER                   <vrptdv_c.h>
#define vreportFileDeviceHEADER                 <vreportf.h>
#define vreportFileDevice_cHEADER               <vrptfd_c.h>
#define vreportFormatHEADER                     <vrepfmt.h>
#define vreportFormat_cHEADER                   <vrepfm_c.h>
#define vreportHEADER                           <vreport.h>
#define vreportLabelItemHEADER                  <vreplabe.h>
#define vreportLabelItem_cHEADER                <vreplb_c.h>
#define vreportLayoutHEADER                     <vreportl.h>
#define vreportLayout_cHEADER                   <vrptlo_c.h>
#define vreportLineItemHEADER                   <vrepline.h>
#define vreportLineItem_cHEADER                 <vrepli_c.h>
#define vreportObjectHEADER                     <vreporto.h>
#define vreportObject_cHEADER                   <vrptob_c.h>
#define vreportOnScreenHEADER                   <vreports.h>
#define vreportOnScreen_cHEADER                 <vrptos_c.h>
#define vreportPrintPreviewHEADER               <vreportp.h>
#define vreportPrintPreview_cHEADER             <vrptpp_c.h>
#define vreportTreeHEADER                       <vreportt.h>
#define vreportTree_cHEADER                     <vrpttr_c.h>
#define vreport_cHEADER                         <vrepor_c.h>
#define vreportdevice_cHEADER                   <vrptdv_c.h>
#define vreportlayout_cHEADER                   <vrptlo_c.h>
#define vreportvarHEADER                        <vrepvar.h>
#define vreportvar_cHEADER                      <vrepva_c.h>
#define vreputilHEADER                          <vreputil.h>
#define vreputil_cHEADER                        <vreput_c.h>
#define vreregHEADER                            <vrereg.h>
#define vresHEADER                              <vres.h>
#define vresfileHEADER                          <vresfile.h>
#define vresfile_cHEADER                        <vresfi_c.h>
#define vresolverHEADER                         <vresolve.h>
#define vresolver_cHEADER                       <vresol_c.h>
#define vresourceHEADER                         <vresourc.h>
#define vresource_cHEADER                       <vresou_c.h>
#define vrestextHEADER                          <vrestext.h>
#define vreutilsHEADER                          <vreutils.h>
#define vrlHEADER                               <vrl.h>
#define vrl_cHEADER                             <vrl_c.h>
#define vrtfHEADER                              <vrtf.h>
#define vrulerHEADER                            <vruler.h>
#define vruler_cHEADER                          <vruler_c.h>
#define vscrapHEADER                            <vscrap.h>
#define vscrap_cHEADER                          <vscrap_c.h>
#define vscribeHEADER                           <vscribe.h>
#define vscribe_cHEADER                         <vscrib_c.h>
#define vseparatorHEADER                        <vsepar.h>
#define vseparator_cHEADER                      <vsepar_c.h>
#define vsequenceHEADER                         <vsequenc.h>
#define vsequence_cHEADER                       <vseque_c.h>
#define vserviceHEADER                          <vservice.h>
#define vservice_cHEADER                        <vservi_c.h>
#define vservicechsrHEADER                      <vsvcchsr.h>
#define vservicechsr_cHEADER                    <vsvcch_c.h>
#define vsessionHEADER                          <vsession.h>
#define vsession_cHEADER                        <vsessi_c.h>
#define vsetjmpHEADER                           <vsetjmp.h>
#define vsignalHEADER                           <vsignal.h>
#define vsignatureGroupHEADER                   <vsiggrp.h>
#define vsignatureGroup_cHEADER                 <vsiggr_c.h>
#define vsignatureHEADER                        <vsignatu.h>
#define vsignature_cHEADER                      <vsigna_c.h>
#define vsingleHEADER                           <vsingle.h>
#define vsizeviewHEADER                         <vsizevie.h>
#define vsizeview_cHEADER                       <vsizev_c.h>
#define vsliderHEADER                           <vslider.h>
#define vslider_cHEADER                         <vslide_c.h>
#define vsockHEADER                             <vsock.h>
#define vsocksysHEADER                          <vsocksys.h>
#define vsockmacHEADER                          <vsockmac.h>
#define vsockos2HEADER                          <vsockos2.h>
#define vsocktcpHEADER                          <vsocktcp.h>
#define vsockudpHEADER                          <vsockudp.h>
#define vsockunxHEADER                          <vsockunx.h>
#define vsockwinHEADER                          <vsockwin.h>
#define vspinnerHEADER                          <vspinner.h>
#define vspinner_cHEADER                        <vspinn_c.h>
#define vsplitHEADER                            <vsplit.h>
#define vsplit_cHEADER                          <vsplit_c.h>
#define vsplitterHEADER                         <vsplitte.h>
#define vspringHEADER                           <vspring.h>
#define vspring_cHEADER                         <vsprin_c.h>
#define vspringdomHEADER                        <vsprdom.h>
#define vspringdom_cHEADER                      <vsprdo_c.h>
#define vspringviewHEADER                       <vsprview.h>
#define vstartupHEADER                          <vstartup.h>
#define vstartup_cHEADER                        <vstart_c.h>
#define vstatusHEADER                           <vstatus.h>
#define vstatusbarHEADER                        <vstatusb.h>
#define vstatusbar_cHEADER                      <vstatb_c.h>
#define vstdHEADER                              <vstd.h>
#define vstdargHEADER                           <vstdarg.h>
#define vstddefHEADER                           <vstddef.h>
#define vstdioHEADER                            <vstdio.h>
#define vstdiosysHEADER                         <vstdiosy.h>
#define vstdlibHEADER                           <vstdlib.h>
#define vstrHEADER                              <vstr.h>
#define vstr_cHEADER                            <vstr_c.h>
#define vstrchsrHEADER                          <vstrchsr.h>
#define vstrchsr_cHEADER                        <vstrch_c.h>
#define vstreamHEADER                           <vstream.h>
#define vstream_cHEADER                         <vstrea_c.h>
#define vstringHEADER                           <vstring.h>
#define vstritemHEADER                          <vstritem.h>
#define vstritem_cHEADER                        <vstrit_c.h>
#define vstylechsrHEADER                        <vstylech.h>
#define vstylechsr_cHEADER                      <vstyle_c.h>
#define vsysHEADER                              <vsys.h>
#define vsysdirHEADER                           <vsysdir.h>
#define vsysfileHEADER                          <vsysfile.h>
#define vsysioctlHEADER                         <vsysioct.h>
#define vsysipcHEADER                           <vsysipc.h>
#define vsysmntentHEADER                        <vsysmnte.h>
#define vsysparamHEADER                         <vsyspara.h>
#define vsysresourceHEADER                      <vsysreso.h>
#define vsysselectHEADER                        <vsyssele.h>
#define vsysshmHEADER                           <vsysshm.h>
#define vsyssocketHEADER                        <vsyssock.h>
#define vsysstatHEADER                          <vsysstat.h>
#define vsyssysteminfoHEADER                    <vsysinfo.h>
#define vsystimeHEADER                          <vsystime.h>
#define vsystimesHEADER                         <vsystims.h>
#define vsystypesHEADER                         <vsystype.h>
#define vsysuioHEADER                           <vsysuio.h>
#define vsysunHEADER                            <vsysun.h>
#define vsysutsnameHEADER                       <vsysutsn.h>
#define vsyswaitHEADER                          <vsyswait.h>
#define vtableviewHEADER                        <vtablevi.h>
#define vtableview_cHEADER                      <vtblv_c.h>
#define vtermHEADER                             <vterm.h>
#define vtestHEADER                             <vtest.h>
#define vtest_cHEADER                           <vtest_c.h>
#define vtextHEADER                             <vtext.h>
#define vtext_cHEADER                           <vtext_c.h>
#define vtextitemHEADER                         <vtextite.h>
#define vtextitem_cHEADER                       <vtexti_c.h>
#define vtextmarkerHEADER                       <vtextmar.h>
#define vtextmarker_cHEADER                     <vtextm_c.h>
#define vtextrulerHEADER                        <vtextrul.h>
#define vtextruler_cHEADER                      <vtextr_c.h>
#define vtextselectionHEADER                    <vtextsel.h>
#define vtextselection_cHEADER                  <vtexts_c.h>
#define vtextviewHEADER                         <vtextvie.h>
#define vtextview_cHEADER                       <vtextv_c.h>
#define vthreadHEADER                           <vthread.h>
#define vthread_cHEADER                         <vthrea_c.h>
#define vthreaderHEADER                         <vthreade.h>
#define vthreadersysHEADER                      <vthrdrss.h>
#define vthreadsysHEADER                        <vthreads.h>
#define vthreadsys_cHEADER                      <vthrds_c.h>
#define vtimeHEADER                             <vtime.h>
#define vtimerHEADER                            <vtimer.h>
#define vtimer_cHEADER                          <vtimer_c.h>
#define vtimestampHEADER                        <vtimesta.h>
#define vtimestamp_cHEADER                      <vtimes_c.h>
#define vtimestampsysHEADER                     <vstmpsys.h>
#define vtoolbarHEADER                          <vtoolbar.h>
#define vtoolbar_cHEADER                        <vtoolb_c.h>
#define vtoolbarRearrangerHEADER                <vtbrearr.h>
#define vtoolbarRearranger_cHEADER              <vtbrar_c.h>
#define vtoolbarSeparatorHEADER                 <vtbsepar.h>
#define vtoolbarSeparator_cHEADER               <vtbsep_c.h>
#define vtoolbuttonHEADER                       <vtoolbtn.h>
#define vtoolbutton_cHEADER                     <vtolbt_c.h>
#define vtoolchangerHEADER                      <vtolchgr.h>
#define vtoolchanger_cHEADER                    <vtolch_c.h>
#define vtooltipHEADER                          <vtooltip.h>
#define vtooltip_cHEADER                        <vtoolt_c.h>
#define vtransformHEADER                        <vtransfo.h>
#define vtransform_cHEADER                      <vtrans_c.h>
#define vtranslatorHEADER                       <vtrans.h>
#define vtranslator_cHEADER                     <vtrnsl_c.h>
#define vtreeHEADER                             <vtree.h>
#define vtree_cHEADER                           <vtree_c.h>
#define vtreecardHEADER                         <vtreecar.h>
#define vtreecard_cHEADER                       <vtreec_c.h>
#define vtreelistHEADER                         <vtreelis.h>
#define vtreelist_cHEADER                       <vtreel_c.h>
#define vtreeviewHEADER                         <vtreevie.h>
#define vtreeview_cHEADER                       <vtreev_c.h>
#define vtypeditemHEADER                        <vtypedit.h>
#define vtypeditem_cHEADER                      <vtypdi_c.h>
#define vulimitHEADER                           <vulimit.h>
#define vulongitemHEADER                        <vulongit.h>
#define vulongitem_cHEADER                      <vulngi_c.h>
#define vundoHEADER                             <vundo.h>
#define vundo_cHEADER                           <vundo_c.h>
#define vundocompatHEADER                       <vundocom.h>
#define vunistdHEADER                           <vunistd.h>
#define vurlHEADER                              <vurl.h>
#define vurl_cHEADER                            <vurl_c.h>
#define vutHEADER                               <vut.h>
#define vutimeHEADER                            <vutime.h>
#define vvaluesHEADER                           <vvalues.h>
#define vvarrayHEADER                           <vvarray.h>
#define vvaxfloatHEADER                         <vvaxfloa.h>
#define vvintHEADER                             <vvint.h>
#define vvmstypesHEADER                         <vvmstype.h>
#define vwaitos2HEADER                          <vwaitos2.h>
#define vwaitunxHEADER                          <vwaitunx.h>
#define vwebbrowseHEADER                        <vwebbrow.h>
#define vwebbrowse_cHEADER                      <vwebbr_c.h>
#define vwindowHEADER                           <vwindow.h>
#define vwindow_cHEADER                         <vwindo_c.h>
#define vwindowsysHEADER                        <vwindows.h>
#define vx11HEADER                              <vx11.h>
#define vx11cursorfontHEADER                    <vx11curs.h>
#define vx11extensionsxshmHEADER                <vx11exte.h>
#define vx11keysymHEADER                        <vx11keys.h>
#define vx11xatomHEADER                         <vx11xato.h>
#define vx11xlibHEADER                          <vx11xlib.h>
#define vx11xutilHEADER                         <vx11xuti.h>
#define vxxloadableHEADER                       <vxxloada.h>

#else /* if (vhdrmodeSHORT_NAMES) */

#define vabstractHEADER                         <vabstract.h>
#define vacceptHEADER                           <vaccept.h>
#define vaccept_cHEADER                         <vaccept_c.h>
#define vappframeHEADER                         <vappframe.h>
#define vappframe_cHEADER                       <vappframe_c.h>
#define vapplicationHEADER                      <vapplication.h>
#define vapplication_cHEADER                    <vapplication_c.h>
#define vargscrapHEADER                         <vargscrap.h>
#define varpainetHEADER                         <varpainet.h>
#define varrayHEADER                            <varray.h>
#define vassertHEADER                           <vassert.h>
#define vatHEADER                               <vat.h>
#define vattributeHEADER                        <vattribute.h>
#define vattribute_cHEADER                      <vattribute_c.h>
#define vblockHEADER                            <vblock.h>
#define vboolitemHEADER                         <vboolitem.h>
#define vboolitem_cHEADER                       <vboolitem_c.h>
#define vbtreeHEADER                            <vbtree.h>
#define vbtree_cHEADER                          <vbtree_c.h>
#define vbufferHEADER                           <vbuffer.h>
#define vbuffer_cHEADER                         <vbuffer_c.h>
#define vbuildNumberHEADER                      <vbldnum.h>
#define vbuildstrsHEADER                        <vbuildstrs.h>
#define vbuildstrsSOURCE                        <vbuildstrs.c>
#define vbuttonHEADER                           <vbutton.h>
#define vbutton_cHEADER                         <vbutton_c.h>
#define vcanvasHEADER                           <vcanvas.h>
#define vcanvas_cHEADER                         <vcanvas_c.h>
#define vcharHEADER                             <vchar.h>
#define vchar_cHEADER                           <vchar_c.h>
#define vcharencodingHEADER                     <vcharencoding.h>
#define vcharencoding_cHEADER                   <vcharencoding_c.h>
#define vchunkHEADER                            <vchunk.h>
#define vclassHEADER                            <vclass.h>
#define vclass_cHEADER                          <vclass_c.h>
#define vclassextraHEADER                       <vclassextra.h>
#define vclassinfoHEADER                        <vclassinfo.h>
#define vclassregHEADER                         <vclassreg.h>
#define vclexHEADER                             <vclex.h>
#define vclientHEADER                           <vclient.h>
#define vclient_cHEADER                         <vclient_c.h>
#define vclipboardHEADER                        <vclipboard.h>
#define vclipboard_cHEADER                      <vclipboard_c.h>
#define vcmdchsrHEADER                          <vcmdchsr.h>
#define vcmdchsr_cHEADER                        <vcmdchsr_c.h>
#define vcolorHEADER                            <vcolor.h>
#define vcolor_cHEADER                          <vcolor_c.h>
#define vcolorchsrHEADER                        <vcolorchsr.h>
#define vcolorchsr_cHEADER                      <vcolorchsr_c.h>
#define vcolorsysHEADER                         <vcolorsys.h>
#define vcomboHEADER                            <vcombo.h>
#define vcombo_cHEADER                          <vcombo_c.h>
#define vcomboboxHEADER                         <vcombobox.h>
#define vcombobox_cHEADER                       <vcombobox_c.h>
#define vcommChannelHEADER                      <vcommchn.h>
#define vcommChannel_cHEADER                    <vcommchn_c.h>
#define vcommHEADER                             <vcomm.h>
#define vcomm_cHEADER                           <vcomm_c.h>
#define vcommandHEADER                          <vcommand.h>
#define vcommand_cHEADER                        <vcommand_c.h>
#define vcommdllHEADER                          <vcommdll.h>
#define vcommfixHEADER                          <vcommfix.h>
#define vconditionHEADER                        <vcondition.h>
#define vconfirmHEADER                          <vconfirm.h>
#define vconfirm_cHEADER                        <vconfirm_c.h>
#define vcontainerGridHEADER                    <vctrgrid.h>
#define vcontainerGrid_cHEADER                  <vctrgrid_c.h>
#define vcontainerHEADER                        <vcontain.h>
#define vcontainer_cHEADER                      <vcontain_c.h>
#define vcontrolHEADER                          <vcontrol.h>
#define vcontrol_cHEADER                        <vcontrol_c.h>
#define vctlchsrHEADER                          <vctlchsr.h>
#define vctlchsr_cHEADER                        <vctlchsr_c.h>
#define vctypeHEADER                            <vctype.h>
#define vcursorHEADER                           <vcursor.h>
#define vcursor_cHEADER                         <vcursor_c.h>
#define vdasdictHEADER                          <vdasdict.h>
#define vdasservHEADER                          <vdasserv.h>
#define vdasserv_cHEADER                        <vdasserv_c.h>
#define vdatasourceChooserHEADER                <vdschsr.h>
#define vdatasourceChooser_cHEADER              <vdschsr_c.h>
#define vdatasourceDataHEADER                   <vdsdata.h>
#define vdatasourceData_cHEADER                 <vdsdata_c.h>
#define vdatasourceDatabaseEngineHEADER         <vdsdbeng.h>
#define vdatasourceDatabaseEngine_cHEADER       <vdsdbeng_c.h>
#define vdatasourceFileSysEngineHEADER          <vdsfseng.h>
#define vdatasourceFileSysEngine_cHEADER        <vdsfseng_c.h>
#define vdatasourceHEADER                       <vdatasource.h>
#define vdatasourceUserInterfaceEngineHEADER    <vdsuieng.h>
#define vdatasourceUserInterfaceEngine_cHEADER  <vdsuieng_c.h>
#define vdatasource_cHEADER                     <vdatasource_c.h>
#define vdatatagHEADER                          <vdatatag.h>
#define vdatatag_cHEADER                        <vdatatag_c.h>
#define vdateHEADER                             <vdate.h>
#define vdate_cHEADER                           <vdate_c.h>
#define vdateitemHEADER                         <vdateitem.h>
#define vdateitem_cHEADER                       <vdateitem_c.h>
#define vdbHEADER                               <vdb.h>
#define vdbServiceHEADER                        <vdbserv.h>
#define vdb_cHEADER                             <vdb_c.h>
#define vdbchsrHEADER                           <vdbchsr.h>
#define vdbchsr_cHEADER                         <vdbchsr_c.h>
#define vdbcomboboxHEADER                       <vdbcombobox.h>
#define vdbformHEADER                           <vdbform.h>
#define vdblistHEADER                           <vdblist.h>
#define vdbmenuHEADER                           <vdbmenu.h>
#define vdbprivHEADER                           <vdbpriv.h>
#define vdbqueryHEADER                          <vdbquery.h>
#define vdbquerybuilderHEADER                   <vdbqb.h>
#define vdbspecHEADER                           <vdbspec.h>
#define vdbspinnerHEADER                        <vdbspinner.h>
#define vdebugHEADER                            <vdebug.h>
#define vdebug_cHEADER                          <vdebug_c.h>
#define vdebugutHEADER                          <vdebugut.h>
#define vdelegatorHEADER                        <vdelegator.h>
#define vdelegator_cHEADER                      <vdelegator_c.h>
#define vdialogHEADER                           <vdialog.h>
#define vdialogItemHEADER                       <vdialog.h>
#define vdialog_cHEADER                         <vdialog_c.h>
#define vdialogsysHEADER                        <vdialsys.h>
#define vdictHEADER                             <vdict.h>
#define vdict_cHEADER                           <vdict_c.h>
#define vdirentHEADER                           <vdirent.h>
#define vdockHEADER                             <vdock.h>
#define vdock_cHEADER                           <vdock_c.h>
#define vdockcontainerHEADER                    <vdockcont.h>
#define vdockcontainer_cHEADER                  <vdockcont_c.h>
#define vdockerHEADER                           <vdocker.h>
#define vdocker_cHEADER                         <vdocker_c.h>
#define vdockitemHEADER                         <vdockitem.h>
#define vdockitem_cHEADER                       <vdockitem_c.h>
#define vdomainHEADER                           <vdomain.h>
#define vdomain_cHEADER                         <vdomain_c.h>
#define vdomainitemHEADER                       <vdomitem.h>
#define vdomainitem_cHEADER                     <vdomitem_c.h>
#define vdomainviewHEADER                       <vdomview.h>
#define vdomainview_cHEADER                     <vdomview_c.h>
#define vdoubleHEADER                           <vdouble.h>
#define vdoubleitemHEADER                       <vdoubleitem.h>
#define vdoubleitem_cHEADER                     <vdoubleitem_c.h>
#define vdragHEADER                             <vdrag.h>
#define vdrag_cHEADER                           <vdrag_c.h>
#define vdrawHEADER                             <vdraw.h>
#define vdraw_cHEADER                           <vdraw_c.h>
#define vdrawcontextHEADER                      <vdrawcontext.h>
#define vdrawcontext_cHEADER                    <vdrawcontext_c.h>
#define vdrawpathHEADER                         <vdrawpath.h>
#define vdrawpath_cHEADER                       <vdrawpath_c.h>
#define vdrawpenHEADER                          <vdrawpen.h>
#define vdrawpen_cHEADER                        <vdrawpen_c.h>
#define vdrawrectsetHEADER                      <vdrawrectset.h>
#define vdrawrectset_cHEADER                    <vdrawrectset_c.h>
#define vdrawsysHEADER                          <vdrawsys.h>
#define vdropHEADER                             <vdropsite.h> /* !!! remove */
#define vdrop_cHEADER                           <vdropsite_c.h> /* !!! remove */
#define vdropsiteHEADER                         <vdropsite.h>
#define vdropsite_cHEADER                       <vdropsite_c.h>
#define vdsdbeng_cHEADER                        <vdsdbeng_c.h>
#define vdsfseng_cHEADER                        <vdsfseng_c.h>
#define vdsuieng_cHEADER                        <vdsuieng_c.h>
#define verrnoHEADER                            <verrno.h>
#define vevent2HEADER                           <vevent2.h>
#define vevent2_cHEADER                         <vevent2_c.h>
#define vevent2sysHEADER                        <vevent2sys.h>
#define vevent2sys_cHEADER                      <vevent2sys_c.h>
#define veventHEADER                            <vevent.h>
#define vevent_cHEADER                          <vevent_c.h>
#define veventsysHEADER                         <veventsys.h>
#define veventsys_cHEADER                       <veventsys_c.h>
#define vevntitrHEADER                          <vevntitr.h>
#define vevntitr_cHEADER                        <vevntitr_c.h>
#define vexHEADER                               <vex.h>
#define vex_cHEADER                             <vex_c.h>
#define vexportHEADER                           <vexport.h>
#define vexsysHEADER                            <vexsys.h>
#define vfcntlHEADER                            <vfcntl.h>
#define vfieldHEADER                            <vfield.h>
#define vfield_cHEADER                          <vfield_c.h>
#define vfileHEADER                             <vfile.h>
#define vfile_cHEADER                           <vfile_c.h>
#define vfilechsrHEADER                         <vfilechsr.h>
#define vfilechsr_cHEADER                       <vfilechsr_c.h>
#define vfixedHEADER                            <vfixed.h>
#define vfixed_cHEADER                          <vfixed_c.h>
#define vfloatHEADER                            <vfloat.h>
#define vfontHEADER                             <vfont.h>
#define vfont_cHEADER                           <vfont_c.h>
#define vfontchsrHEADER                         <vfontchsr.h>
#define vfontchsr_cHEADER                       <vfontchsr_c.h>
#define vfontspecHEADER                         <vfontspec.h>
#define vfontspec_cHEADER                       <vfontspec_c.h>
#define vfontsysHEADER                          <vfontsys.h>
#define vformContextHEADER                      <vformctxt.h>
#define vformContext_cHEADER                    <vformctxt_c.h>
#define vformHEADER                             <vform.h>
#define vform_cHEADER                           <vform_c.h>
#define vformatHEADER                           <vformat.h>
#define vformat_cHEADER                         <vformat_c.h>
#define vfsHEADER                               <vfs.h>
#define vfs_cHEADER                             <vfs_c.h>
#define vgalaxyBuildNumberHEADER                <vgalbnum.h>
#define vgalaxyHEADER                           <vgalaxy.h>
#define vglitemHEADER                           <vglitem.h>
#define vglwinHEADER                            <vglwin.h>
#define vgraphHEADER                            <vgraph.h>
#define vgridcontainerHEADER                    <vgridcont.h>
#define vgridcontainer_cHEADER                  <vgridcont_c.h>
#define vgridmodelHEADER                        <vgridmodel.h>
#define vgridmodel_cHEADER                      <vgridmodel_c.h>
#define vgrpHEADER                              <vgrp.h>
#define vhdrdefsHEADER                          <vhdrdefs.h>
#define vhdrmodeHEADER                          <vhdrmode.h>
#define vhelpHEADER                             <vhelp.h>
#define vhelpRunnableHEADER                     <vhelprun.h>
#define vhelp_cHEADER                           <vhelp_c.h>
#define vhelpdasHEADER                          <vhelpdas.h>
#define vhelpdisplayHEADER                      <vhelpdisplay.h>
#define vhelpdisplay_cHEADER                    <vhelpdisplay_c.h>
#define vhelpdocHEADER                          <vhelpdoc.h>
#define vhelpdefaultHEADER                      <vhelpdefault.h>
#define vhelpdefault_cHEADER                    <vhelpdefault_c.h>
#define vhelpexplorerHEADER                     <vhelpexplorer.h>
#define vhelpexplorer_cHEADER                   <vhelpexplorer_c.h>
#define vhelpgalaxyHEADER                       <vhelpgalaxy.h>
#define vhelpgalaxy_cHEADER                     <vhelpgalaxy_c.h>
#define vhelphtmlgalaxyHEADER                   <vhelphtmlgalaxy.h>
#define vhelphtmlgalaxy_cHEADER                 <vhelphtmlgalaxy_c.h>
#define vhelphtmllocatorHEADER                  <vhelphtmllocator.h>
#define vhelphtmllocator_cHEADER                <vhelphtmllocator_c.h>
#define vhelphypertextHEADER                    <vhelphypertext.h>
#define vhelphypertext_cHEADER                  <vhelphypertext_c.h>
#define vhelplinkerHEADER                       <vhelplinker.h>
#define vhelplocatorHEADER                      <vhelplocator.h>
#define vhelplocator_cHEADER                    <vhelplocator_c.h>
#define vhelpnetscapeHEADER                     <vhelpnetscape.h>
#define vhelpnetscape_cHEADER                   <vhelpnetscape_c.h>
#define vhelpobjectHEADER                       <vhelpobject.h>
#define vhelpobject_cHEADER                     <vhelpobject_c.h>
#define vhelprefHEADER                          <vhelpref.h>
#define vhelpref_cHEADER                        <vhelpref_c.h>
#define vhelpreflocatorHEADER                   <vhelpreflocator.h>
#define vhelpreflocator_cHEADER                 <vhelpreflocator_c.h>
#define vhelpregistryHEADER                     <vhelpregistry.h>
#define vhelpregistry_cHEADER                   <vhelpregistry_c.h>
#define vhelprequestHEADER                      <vhelprequest.h>
#define vhelprequest_cHEADER                    <vhelprequest_c.h>
#define vhelpstatusHEADER                       <vhelpstatus.h>
#define vhelpstatus_cHEADER                     <vhelpstatus_c.h>
#define vhelptextHEADER                         <vhelptext.h>
#define vhelptext_cHEADER                       <vhelptext_c.h>
#define vhelptextlocatorHEADER                  <vhelptextlocator.h>
#define vhelptextlocator_cHEADER                <vhelptextlocator_c.h>
#define vhelptooltipHEADER                      <vhelptooltip.h>
#define vhelptooltip_cHEADER                    <vhelptooltip_c.h>
#define vhelptransHEADER                        <vhelptrans.h>
#define vhelpwinhelpHEADER                      <vhelpwinhelp.h>
#define vhelpwinhelp_cHEADER                    <vhelpwinhelp_c.h>
#define vhexHEADER                              <vhex.h>
#define vhex_cHEADER                            <vhex_c.h>
#define vhexchsrHEADER                          <vhexchsr.h>
#define vhexchsr_cHEADER                        <vhexchsr_c.h>
#define vhtmlHEADER                             <vhtml.h>
#define vhtmledHEADER                           <vhtmled.h>
#define vi18nHEADER                             <vi18n.h>
#define viconviewHEADER                         <viconview.h>
#define viconview_cHEADER                       <viconview_c.h>
#define vimageHEADER                            <vimage.h>
#define vimage_cHEADER                          <vimage_c.h>
#define vimageedtrHEADER                        <vimageed.h>
#define vimageedtr_cHEADER                      <vimageed_c.h>
#define vimgedHEADER                            <vimged.h>
#define vimgedutilsHEADER                       <vimgedutils.h>
#define vimgutilsHEADER                         <vimgutils.h>
#define vimportHEADER                           <vimport.h>
#define vinputHEADER                            <vinput.h>
#define vinput_cHEADER                          <vinput_c.h>
#define vinputsysHEADER                         <vinputsys.h>
#define vinstHEADER                             <vinst.h>
#define vinst_cHEADER                           <vinst_c.h>
#define vinstallHEADER                          <vinstall.h>
#define vinstall_cHEADER                        <vinstall_c.h>
#define vinstanceHEADER                         <vinstance.h>
#define vinstance_cHEADER                       <vinstance_c.h>
#define vinterfaceHEADER                        <vinterface.h>
#define vinterface_cHEADER                      <vinterface_c.h>
#define vioHEADER                               <vio.h>
#define viteratorHEADER                         <viterator.h>
#define viterator_cHEADER                       <viterator_c.h>
#define vkeyHEADER                              <vkey.h>
#define vkey_cHEADER                            <vkey_c.h>
#define vkeyitemHEADER                          <vkeyitem.h>
#define vkeyitem_cHEADER                        <vkeyitem_c.h>
#define vkeysysHEADER                           <vkeysys.h>
#define vkindHEADER                             <vkind.h>
#define vlafHEADER                              <vlaf.h>
#define vlaf_cHEADER                            <vlaf_c.h>
#define vlibcHEADER                             <vlibc.h>
#define vlimitsHEADER                           <vlimits.h>
#define vlistHEADER                             <vlist.h>
#define vlist_cHEADER                           <vlist_c.h>
#define vlisteditHEADER                         <vlistedit.h>
#define vlistitemHEADER                         <vlistitem.h>
#define vlistitem_cHEADER                       <vlistitem_c.h>
#define vlistselectionHEADER                    <vlistsel.h>
#define vlistselection_cHEADER                  <vlistsel_c.h>
#define vlistsizeHEADER                         <vlistsize.h>
#define vlistsize_cHEADER                       <vlistsize_c.h>
#define vliststrHEADER                          <vliststr.h>
#define vliststr_cHEADER                        <vliststr_c.h>
#define vlistviewHEADER                         <vlistview.h>
#define vlistview_cHEADER                       <vlistview_c.h>
#define vloadableHEADER                         <vloadable.h>
#define vloadable_cHEADER                       <vloadable_c.h>
#define vlocaleHEADER                           <vlocale.h>
#define vlockHEADER                             <vlock.h>
#define vlongitemHEADER                         <vlongitem.h>
#define vlongitem_cHEADER                       <vlongitem_c.h>
#define vlonglongHEADER                         <vlonglong.h>
#define vlonglong_cHEADER                       <vlonglong_c.h>
#define vmaccontrolsHEADER                      <vmaccontrols.h>
#define vmacdialogsHEADER                       <vmacdialogs.h>
#define vmacerrorsHEADER                        <vmacerrors.h>
#define vmaceventsHEADER                        <vmacevents.h>
#define vmacfilesHEADER                         <vmacfiles.h>
#define vmacfontsHEADER                         <vmacfonts.h>
#define vmacgestaltequHEADER                    <vmacgestaltequ.h>
#define vmachineHEADER                          <vmachine.h>
#define vmachine_cHEADER                        <vmachine_c.h>
#define vmacmemoryHEADER                        <vmacmemory.h>
#define vmacquickdrawHEADER                     <vmacquickdraw.h>
#define vmacresourcesHEADER                     <vmacresources.h>
#define vmacscriptHEADER                        <vmacscript.h>
#define vmacstringsHEADER                       <vmacstrings.h>
#define vmacsysequHEADER                        <vmacsysequ.h>
#define vmactypesHEADER                         <vmactypes.h>
#define vmacwindowsHEADER                       <vmacwindows.h>
#define vmaindialogHEADER                       <vmaindia.h>
#define vmainviewHEADER                         <vmainvie.h>
#define vmainview_cHEADER                       <vmainvie_c.h>
#define vmappingHEADER                          <vmapping.h>
#define vmapping_cHEADER                        <vmapping_c.h>
#define vmaskitemHEADER                         <vmaskitem.h>
#define vmaskitem_cHEADER                       <vmaskitem_c.h>
#define vmathHEADER                             <vmath.h>
#define vmatrixHEADER                           <vmatrix.h>
#define vmatrix_cHEADER                         <vmatrix_c.h>
#define vmemHEADER                              <vmem.h>
#define vmem_cHEADER                            <vmem_c.h>
#define vmemsysHEADER                           <vmemsys.h>
#define vmenuHEADER                             <vmenu.h>
#define vmenu_cHEADER                           <vmenu_c.h>
#define vmenubarHEADER                          <vmenubar.h>
#define vmenubar_cHEADER                        <vmenubar_c.h>
#define vmessageHEADER                          <vmessage.h>
#define vmoduleHEADER                           <vmodule.h>
#define vmodule_cHEADER                         <vmodule_c.h>
#define vmswhdrsHEADER                          <vmswhdrs.h>
#define vmutexHEADER                            <vmutex.h>
#define vmutexsysHEADER                         <vmutexsys.h>
#define vnameHEADER                             <vname.h>
#define vname_cHEADER                           <vname_c.h>
#define vnameobjectHEADER                       <vnameobj.h>
#define vnameobject_cHEADER                     <vnameobj_c.h>
#define vndxHEADER                              <vndx.h>
#define vnetdbHEADER                            <vnetdb.h>
#define vnetinetinHEADER                        <vnetinetin.h>
#define vnotebookHEADER                         <vnotebook.h>
#define vnotebook_cHEADER                       <vnotebook_c.h>
#define vnoticeHEADER                           <vnotice.h>
#define vnotice_cHEADER                         <vnotice_c.h>
#define vnumHEADER                              <vnum.h>
#define vnum_cHEADER                            <vnum_c.h>
#define vobjectHEADER                           <vobject.h>
#define vobject_cHEADER                         <vobject_c.h>
#define vobservableHEADER                       <vobservable.h>
#define vobservable_cHEADER                     <vobservable_c.h>
#define vobserverHEADER                         <vobserver.h>
#define vobserver_cHEADER                       <vobserver_c.h>
#define voccurrenceHEADER                       <voccurrence.h>
#define voccurrence_cHEADER                     <voccurrence_c.h>
#define vodbcHEADER                             <vodbc.h>
#define voleHEADER                              <vole.h>
#define vole_cHEADER                            <vole_c.h>
#define volectrlHEADER                          <volectrl.h>
#define volectrl_cHEADER                        <volectrl_c.h>
#define volesiteHEADER                          <volesite.h>
#define volesite_cHEADER                        <volesite_c.h>
#define volevariantHEADER                       <volevariant.h>
#define volevariant_cHEADER                     <volevariant_c.h>
#define volegenHEADER                           <volegen.h>
#define volegen_cHEADER                         <volegen_c.h>
#define vos2HEADER                              <vos2.h>
#define vpaledHEADER                            <vpaled.h>
#define vpaletteHEADER                          <vpalette.h>
#define vpalette_cHEADER                        <vpalette_c.h>
#define vpanecontainerHEADER                    <vpanecont.h>
#define vpanecontainer_cHEADER                  <vpanecont_c.h>
#define vpathscrapHEADER                        <vpthscrp.h>
#define vpathscrap_cHEADER                      <vpthscrp_c.h>
#define vpersistentHEADER                       <vpersistent.h>
#define vpersistent_cHEADER                     <vpersistent_c.h>
#define vpixmapHEADER                           <vpixmap.h>
#define vpixmap_cHEADER                         <vpixmap_c.h>
#define vpointHEADER                            <vpoint.h>
#define vpoint_cHEADER                          <vpoint_c.h>
#define vpoolHEADER                             <vpool.h>
#define vpool_cHEADER                           <vpool_c.h>
#define vportHEADER                             <vport.h>
#define vportenvHEADER                          <vportenv.h>
#define vportmacHEADER                          <vportmac.h>
#define vpqHEADER                               <vpq.h>
#define vpq_cHEADER                             <vpq_c.h>
#define vprefHEADER                             <vpref.h>
#define vpref_cHEADER                           <vpref_c.h>
#define vprintHEADER                            <vprint.h>
#define vprint_cHEADER                          <vprint_c.h>
#define vprintsysHEADER                         <vprintsys.h>
#define vprocessHEADER                          <vprocess.h>
#define vprocess_cHEADER                        <vprocess_c.h>
#define vpscontextHEADER                        <vpscontext.h>
#define vpsdictHEADER                           <vpsdict.h>
#define vpserrorHEADER                          <vpserror.h>
#define vpsfileHEADER                           <vpsfile.h>
#define vpsinterpHEADER                         <vpsinterp.h>
#define vpsobjectHEADER                         <vpsobject.h>
#define vpsopHEADER                             <vpsop.h>
#define vpsscanHEADER                           <vpsscan.h>
#define vpsstackHEADER                          <vpsstack.h>
#define vpsvmHEADER                             <vpsvm.h>
#define vpwdHEADER                              <vpwd.h>
#define vpwditemHEADER                          <vpwditem.h>
#define vpwditem_cHEADER                        <vpwditem_c.h>
#define vqueryHEADER                            <vquery.h>
#define vqueryvalueHEADER                       <vqueryvalue.h>
#define vquerybuilderHEADER                     <vquerybuilder.h>
#define vreHEADER                               <vre.h>
#define vreaderHEADER                           <vreader.h>
#define vrectHEADER                             <vrect.h>
#define vrect_cHEADER                           <vrect_c.h>
#define vredeclHEADER                           <vredecl.h>
#define vreeditorHEADER                         <vreeditor.h>
#define vrefileHEADER                           <vrefile.h>
#define vregexpHEADER                           <vregexp.h>
#define vregexp_cHEADER                         <vregexp_c.h>
#define vreinitHEADER                           <vreinit.h>
#define vrepanelHEADER                          <vrepanel.h>
#define vreplabel_cHEADER                       <vreplabel_c.h>
#define vreplangHEADER                          <vreplang.h>
#define vreplang_cHEADER                        <vreplang_c.h>
#define vreportComponentHEADER                  <vreportcomponent.h>
#define vreportComponent_cHEADER                <vreportcomponent_c.h>
#define vreportDataChooserHEADER                <vrdchsr.h>
#define vreportDataChooser_cHEADER              <vrdchsr_c.h>
#define vreportDeviceChooserHEADER              <vrdevchsr.h>
#define vreportDeviceChooser_cHEADER            <vrdevchsr_c.h>
#define vreportDeviceHEADER                     <vreportdevice.h>
#define vreportDevice_cHEADER                   <vreportdevice_c.h>
#define vreportFileDeviceHEADER                 <vreportfiledev.h>
#define vreportFileDevice_cHEADER               <vreportfiledev_c.h>
#define vreportFormatHEADER                     <vrepfmt.h>
#define vreportFormat_cHEADER                   <vrepfmt_c.h>
#define vreportHEADER                           <vreport.h>
#define vreportLabelItemHEADER                  <vreplabel.h>
#define vreportLabelItem_cHEADER                <vreplabel_c.h>
#define vreportLayoutHEADER                     <vreportlayout.h>
#define vreportLayout_cHEADER                   <vreportlayout_c.h>
#define vreportLineItemHEADER                   <vrepline.h>
#define vreportLineItem_cHEADER                 <vrepline_c.h>
#define vreportObjectHEADER                     <vreportobject.h>
#define vreportObject_cHEADER                   <vreportobject_c.h>
#define vreportOnScreenHEADER                   <vreportscreen.h>
#define vreportOnScreen_cHEADER                 <vreportscreen_c.h>
#define vreportPrintPreviewHEADER               <vreportppv.h>
#define vreportPrintPreview_cHEADER             <vreportppv_c.h>
#define vreportTreeHEADER                       <vreporttree.h>
#define vreportTree_cHEADER                     <vreporttree_c.h>
#define vreport_cHEADER                         <vreport_c.h>
#define vreportdevice_cHEADER                   <vreportdevice_c.h>
#define vreportlayout_cHEADER                   <vreportlayout_c.h>
#define vreportvarHEADER                        <vrepvar.h>
#define vreportvar_cHEADER                      <vrepvar_c.h>
#define vreputilHEADER                          <vreputil.h>
#define vreputil_cHEADER                        <vreputil_c.h>
#define vreregHEADER                            <vrereg.h>
#define vresHEADER                              <vres.h>
#define vresfileHEADER                          <vresfile.h>
#define vresfile_cHEADER                        <vresfile_c.h>
#define vresolverHEADER                         <vresolver.h>
#define vresolver_cHEADER                       <vresolver_c.h>
#define vresourceHEADER                         <vresource.h>
#define vresource_cHEADER                       <vresource_c.h>
#define vrestextHEADER                          <vrestext.h>
#define vreutilsHEADER                          <vreutils.h>
#define vrlHEADER                               <vrl.h>
#define vrl_cHEADER                             <vrl_c.h>
#define vrtfHEADER                              <vrtf.h>
#define vrulerHEADER                            <vruler.h>
#define vruler_cHEADER                          <vruler_c.h>
#define vscrapHEADER                            <vscrap.h>
#define vscrap_cHEADER                          <vscrap_c.h>
#define vscribeHEADER                           <vscribe.h>
#define vscribe_cHEADER                         <vscribe_c.h>
#define vseparatorHEADER                        <vsepar.h>
#define vseparator_cHEADER                      <vsepar_c.h>
#define vsequenceHEADER                         <vsequence.h>
#define vsequence_cHEADER                       <vsequence_c.h>
#define vserviceHEADER                          <vservice.h>
#define vservice_cHEADER                        <vservice_c.h>
#define vservicechsrHEADER                      <vsvcchsr.h>
#define vservicechsr_cHEADER                    <vsvcchsr_c.h>
#define vsessionHEADER                          <vsession.h>
#define vsession_cHEADER                        <vsession_c.h>
#define vsetjmpHEADER                           <vsetjmp.h>
#define vsignalHEADER                           <vsignal.h>
#define vsignatureGroupHEADER                   <vsiggrp.h>
#define vsignatureGroup_cHEADER                 <vsiggrp_c.h>
#define vsignatureHEADER                        <vsignature.h>
#define vsignature_cHEADER                      <vsignature_c.h>
#define vsingleHEADER                           <vsingle.h>
#define vsizeviewHEADER                         <vsizeview.h>
#define vsizeview_cHEADER                       <vsizeview_c.h>
#define vsliderHEADER                           <vslider.h>
#define vslider_cHEADER                         <vslider_c.h>
#define vsockHEADER                             <vsock.h>
#define vsocksysHEADER                          <vsocksys.h>
#define vsockmacHEADER                          <vsockmac.h>
#define vsockos2HEADER                          <vsockos2.h>
#define vsocktcpHEADER                          <vsocktcp.h>
#define vsockudpHEADER                          <vsockudp.h>
#define vsockunxHEADER                          <vsockunx.h>
#define vsockwinHEADER                          <vsockwin.h>
#define vspinnerHEADER                          <vspinner.h>
#define vspinner_cHEADER                        <vspinner_c.h>
#define vsplitHEADER                            <vsplit.h>
#define vsplit_cHEADER                          <vsplit_c.h>
#define vsplitterHEADER                         <vsplitter.h>
#define vspringHEADER                           <vspring.h>
#define vspring_cHEADER                         <vspring_c.h>
#define vspringdomHEADER                        <vsprdom.h>
#define vspringdom_cHEADER                      <vsprdom_c.h>
#define vspringviewHEADER                       <vsprview.h>
#define vstartupHEADER                          <vstartup.h>
#define vstartup_cHEADER                        <vstartup_c.h>
#define vstatusHEADER                           <vstatus.h>
#define vstatusbarHEADER                        <vstatusbar.h>
#define vstatusbar_cHEADER                      <vstatusbar_c.h>
#define vstdHEADER                              <vstd.h>
#define vstdargHEADER                           <vstdarg.h>
#define vstddefHEADER                           <vstddef.h>
#define vstdioHEADER                            <vstdio.h>
#define vstdiosysHEADER                         <vstdiosys.h>
#define vstdlibHEADER                           <vstdlib.h>
#define vstrHEADER                              <vstr.h>
#define vstr_cHEADER                            <vstr_c.h>
#define vstrchsrHEADER                          <vstrchsr.h>
#define vstrchsr_cHEADER                        <vstrchsr_c.h>
#define vstreamHEADER                           <vstream.h>
#define vstream_cHEADER                         <vstream_c.h>
#define vstringHEADER                           <vstring.h>
#define vstritemHEADER                          <vstritem.h>
#define vstritem_cHEADER                        <vstritem_c.h>
#define vstylechsrHEADER                        <vstylechsr.h>
#define vstylechsr_cHEADER                      <vstylechsr_c.h>
#define vsysHEADER                              <vsys.h>
#define vsysdirHEADER                           <vsysdir.h>
#define vsysfileHEADER                          <vsysfile.h>
#define vsysioctlHEADER                         <vsysioctl.h>
#define vsysipcHEADER                           <vsysipc.h>
#define vsysmntentHEADER                        <vsysmntent.h>
#define vsysparamHEADER                         <vsysparam.h>
#define vsysresourceHEADER                      <vsysresource.h>
#define vsysselectHEADER                        <vsysselect.h>
#define vsysshmHEADER                           <vsysshm.h>
#define vsyssocketHEADER                        <vsyssocket.h>
#define vsysstatHEADER                          <vsysstat.h>
#define vsyssysteminfoHEADER                    <vsyssysteminfo.h>
#define vsystimeHEADER                          <vsystime.h>
#define vsystimesHEADER                         <vsystimes.h>
#define vsystypesHEADER                         <vsystypes.h>
#define vsysuioHEADER                           <vsysuio.h>
#define vsysunHEADER                            <vsysun.h>
#define vsysutsnameHEADER                       <vsysutsname.h>
#define vsyswaitHEADER                          <vsyswait.h>
#define vtableviewHEADER                        <vtableview.h>
#define vtableview_cHEADER                      <vtableview_c.h>
#define vtermHEADER                             <vterm.h>
#define vtestHEADER                             <vtest.h>
#define vtest_cHEADER                           <vtest_c.h>
#define vtextHEADER                             <vtext.h>
#define vtext_cHEADER                           <vtext_c.h>
#define vtextitemHEADER                         <vtextitem.h>
#define vtextitem_cHEADER                       <vtextitem_c.h>
#define vtextmarkerHEADER                       <vtextmarker.h>
#define vtextmarker_cHEADER                     <vtextmarker_c.h>
#define vtextrulerHEADER                        <vtextruler.h>
#define vtextruler_cHEADER                      <vtextruler_c.h>
#define vtextselectionHEADER                    <vtextsel.h>
#define vtextselection_cHEADER                  <vtextsel_c.h>
#define vtextviewHEADER                         <vtextview.h>
#define vtextview_cHEADER                       <vtextview_c.h>
#define vthreadHEADER                           <vthread.h>
#define vthread_cHEADER                         <vthread_c.h>
#define vthreaderHEADER                         <vthreader.h>
#define vthreadersysHEADER                      <vthrdrss.h>
#define vthreadsysHEADER                        <vthreadsys.h>
#define vthreadsys_cHEADER                      <vthreadsys_c.h>
#define vtimeHEADER                             <vtime.h>
#define vtimerHEADER                            <vtimer.h>
#define vtimer_cHEADER                          <vtimer_c.h>
#define vtimestampHEADER                        <vtimestamp.h>
#define vtimestamp_cHEADER                      <vtimestamp_c.h>
#define vtimestampsysHEADER                     <vstmpsys.h>
#define vtoolbarHEADER                          <vtoolbar.h>
#define vtoolbar_cHEADER                        <vtoolbar_c.h>
#define vtoolbarRearrangerHEADER                <vtbrearranger.h>
#define vtoolbarRearranger_cHEADER              <vtbrearranger_c.h>
#define vtoolbarSeparatorHEADER                 <vtbsepar.h>
#define vtoolbarSeparator_cHEADER               <vtbsepar_c.h>
#define vtoolbuttonHEADER                       <vtoolbtn.h>
#define vtoolbutton_cHEADER                     <vtoolbtn_c.h>
#define vtoolchangerHEADER                      <vtoolchanger.h>
#define vtoolchanger_cHEADER                    <vtoolchanger_c.h>
#define vtooltipHEADER                          <vtooltip.h>
#define vtooltip_cHEADER                        <vtooltip_c.h>
#define vtransformHEADER                        <vtransform.h>
#define vtransform_cHEADER                      <vtransform_c.h>
#define vtranslatorHEADER                       <vtrans.h>
#define vtranslator_cHEADER                     <vtrans_c.h>
#define vtreeHEADER                             <vtree.h>
#define vtree_cHEADER                           <vtree_c.h>
#define vtreecardHEADER                         <vtreecard.h>
#define vtreecard_cHEADER                       <vtreecard_c.h>
#define vtreelistHEADER                         <vtreelist.h>
#define vtreelist_cHEADER                       <vtreelist_c.h>
#define vtreeviewHEADER                         <vtreeview.h>
#define vtreeview_cHEADER                       <vtreeview_c.h>
#define vtypeditemHEADER                        <vtypeditem.h>
#define vtypeditem_cHEADER                      <vtypeditem_c.h>
#define vulimitHEADER                           <vulimit.h>
#define vulongitemHEADER                        <vulongitem.h>
#define vulongitem_cHEADER                      <vulongitem_c.h>
#define vundoHEADER                             <vundo.h>
#define vundo_cHEADER                           <vundo_c.h>
#define vundocompatHEADER                       <vundocompat.h>
#define vunistdHEADER                           <vunistd.h>
#define vurlHEADER                              <vurl.h>
#define vurl_cHEADER                            <vurl_c.h>
#define vutHEADER                               <vut.h>
#define vutimeHEADER                            <vutime.h>
#define vvaluesHEADER                           <vvalues.h>
#define vvarrayHEADER                           <vvarray.h>
#define vvaxfloatHEADER                         <vvaxfloat.h>
#define vvintHEADER                             <vvint.h>
#define vvmstypesHEADER                         <vvmstypes.h>
#define vwaitos2HEADER                          <vwaitos2.h>
#define vwaitunxHEADER                          <vwaitunx.h>
#define vwebbrowseHEADER                        <vwebbrowse.h>
#define vwebbrowse_cHEADER                      <vwebbrowse_c.h>
#define vwindowHEADER                           <vwindow.h>
#define vwindow_cHEADER                         <vwindow_c.h>
#define vwindowsysHEADER                        <vwindowsys.h>
#define vx11HEADER                              <vx11.h>
#define vx11cursorfontHEADER                    <vx11cursorfont.h>
#define vx11extensionsxshmHEADER                <vx11extensionsxshm.h>
#define vx11keysymHEADER                        <vx11keysym.h>
#define vx11xatomHEADER                         <vx11xatom.h>
#define vx11xlibHEADER                          <vx11xlib.h>
#define vx11xutilHEADER                         <vx11xutil.h>
#define vxxloadableHEADER                       <vxxloadable.h>

#endif /* #if (vhdrmodeSHORT_NAMES) #else */

#endif /* #ifndef vhdrdefsINCLUDED */

/*
 * Local Variables:
 * c-argdecl-indent:                4
 * c-brace-imaginary-offset:        0
 * c-brace-offset:                 -4
 * c-continued-brace-offset:        0
 * c-continued-statement-offset:    4
 * c-extra-brace-offset:            0
 * c-file-offsets:                ((block-open . -))
 * c-file-style:                   "BSD"
 * c-indent-level:                  4
 * c-label-offset:                 -4
 * indent-tabs-mode:                nil
 * tab-width:                       4
 * End:
 */

