# makefile for make-based platforms

ALL_TARGETS =  tut2a$(E) tut3a$(E) tut3b$(E) tut3c$(E) tut4a$(E) tut5a$(E) tut6a$(E) tut7a$(E) tut8a$(E) ex3a$(E) ex4a$(E) ex4b$(E) ex6a$(E) ex7a$(E) ex8a$(E)

!include ..\environ

LDLIBS_HOOK =

tut2aOBJS = tut2a$(O)

LDLIBS_HOOK =

tut3aOBJS = tut3a$(O)

LDLIBS_HOOK =

tut3bOBJS = tut3b$(O)

LDLIBS_HOOK =

tut3cOBJS = tut3c$(O)

LDLIBS_HOOK =

tut4aOBJS = tut4a$(O)

LDLIBS_HOOK =

tut5aOBJS = tut5a$(O)

LDLIBS_HOOK =

tut6aOBJS = tut6a$(O)

LDLIBS_HOOK =

tut7aOBJS = tut7a$(O)

LDLIBS_HOOK =

tut8aOBJS = tut8a$(O) command$(O)

tut8a$(E) : $(tut8aOBJS)
	$(COMPILE_AND_LINK)$@ $(tut8aOBJS) $(LDLIBS)

LDLIBS_HOOK =

ex3aOBJS = ex3a$(O)

LDLIBS_HOOK =

ex4aOBJS = ex4a$(O)

LDLIBS_HOOK =

ex4bOBJS = ex4b$(O)

LDLIBS_HOOK =

ex6aOBJS = ex6a$(O)

LDLIBS_HOOK =

ex7aOBJS = ex7a$(O)

LDLIBS_HOOK =

ex8aOBJS = ex8a$(O)

