#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:40:59 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME	= ../..

SOURCE_DIRS	= \
		imp \
		gen \
		gen_erate \
		#cry \
		env \
		she \
		imp \
		pas \
		gen \
		sim #\
		ooa \

include		${SOURCE_HOME}/make/branch.mk
