#!/bin/sh
#==========================================================================
#
# File:      $RCSfile: comp_private,v $
# Version:   $Revision: 1.11 $
# Modified:  $Date: 2013/03/14 05:36:55 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#
# This script builds BridgePoint in the user's private area
#
# Parameters:
#   $1 - Platform for which this build is intended
#   $2 - Version for which this build is intended

set -e
set -u

if [ $# -lt 2 ]; then
  echo "Usage:
   `basename $0` <platform> <version> <make-parameters>
"
  exit 2
fi

PLATFORM=$1
export PLATFORM
VERSION=$2
export VERSION
shift
shift

DEBUG_BUILD=$1
if [ "$DEBUG_BUILD" = "debug" ]; then
  DEBUG_BUILD=1
  shift
else
  DEBUG_BUILD=0
fi
export DEBUG_BUILD

makeparms=compile
if [ $# -ne 0 ]; then
  makeparms="$*"
fi

# Include file with customizable build information
this_path="`dirname $0`"
if [ "$this_path" = "." ]; then
  this_path="`pwd`"
fi

HOST_INFO_INCLUDE=$this_path/get_host_platform.inc
. $HOST_INFO_INCLUDE

BUILD_INCLUDE=$this_path/build_vars.inc 
. $BUILD_INCLUDE
export BUILD_INCLUDE

pc="%"
date_stamp="`date \"+${pc}y${pc}m${pc}d_${pc}H${pc}M${pc}S\"`"

file_pre=comp
for p in $makeparms
  do
  case $p in
    comp* )
      file_pre=comp
      break
      ;;
    link* )
      file_pre=link
      break
      ;;
    dep* )
      file_pre=dep
      break
      ;;
    scour* )
      file_pre=scour
      if [ -d $BUILD_DIR ]; then
         rm -rf $BUILD_DIR
      fi
      break
      ;;
  esac
  break
  done

# Assure the directories exist
if [ ! -d $BUILD_DIR ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $BUILD_DIR"
  	echo ""
    exit 1
  fi
elif [ ! -d $LOG_DIR ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $LOG_DIR"
  	echo ""
    exit 1
  fi
elif [ ! -d $SCHEMA_DIR ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $SCHEMA_DIR"
  	echo ""
    exit 1
  fi
elif [ ! -d $BP_PRV_SRC ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $BP_PRV_SRC"
  	echo ""
    exit 1
  fi
elif [ ! -d $BP_PRV_BLD ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $BP_PRV_BLD"
  	echo ""
    exit 1
  fi
elif [ ! -d $BP_PRV_PRD ]; then
  if [ "$file_pre" = "link" ]; then
    $this_path/create_prv_and_pub $PLATFORM $VERSION
  else
  	echo ""
    echo "ERROR: Run the create_bp_build script in the project root to create $BP_PRV_PRD"
  	echo ""
    exit 1
  fi
fi

os=`uname -s`
case $os in
  Windows*)
    MAKE=make.exe
    export MAKE
    ;;
  CYGWIN*)
    MAKE=/usr/bin/make
    export MAKE
    ;;
esac

COMP_OUT_FILE=$LOG_DIR/${file_pre}_${VERSION}_${date_stamp}.out

case $file_pre in
  comp)
    {
    echo ""
    echo "Starting time: `date`"
    echo "Host: `hostname`"
    cd $BP_PRV_SRC
    cmd="$MAKE -f $BP_PRV_SRC/makefile $makeparms"
    echo "$cmd"
    $cmd
    echo "Ending time: `date`"
    } 2>&1 |
    tee $COMP_OUT_FILE
#
#    sed "s!^\"$MC_DBMS_ROOTDIR.*\$!DELETELINE!
#         s!^..*Warning:..*two consecutive underbars..*\$!DELETELINE!
#         s!^..*\.hh\", line..*Warning:..*is defined but not used.*\$!DELETELINE!
#         s!^..*Warning:..*hides the function..*\$!DELETELINE!
#         s!^..*Where: While specializing..*\$!DELETELINE!
#         s!^..*Where: Specialized in non-template code.*\$!DELETELINE!
#         /^..*Warning(s) detected/s/^/  /
#         /^DELETELINE$/d" |
#
    ;;
  *)
    {
    echo "Starting time: `date`"
    echo "Host: `hostname`"
    cd $BP_PRV_SRC
    cmd="$MAKE -f $BP_PRV_SRC/makefile $makeparms"
    echo "$cmd"
    $cmd
    echo "Ending time: `date`"
    } 2>&1 | tee $COMP_OUT_FILE
    ;;
esac
