#!/bin/sh
#==========================================================================
#
# File:      $RCSfile: rename_private,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:42:20 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#
# This script builds BridgePoint in the user's private area
#
# Parameters:
#   $1 - Platform for which this build is intended

set -e
set -u

execname=`basename $0`
if [ $# -lt 1 ]; then
  echo "Usage:
   $execname <platform> ...
"
  exit 2
fi

PLATFORM=$1

this_path=`dirname $0`
if [ "$this_path" = "." ]; then
  this_path="`pwd`"
fi

$this_path/$PLATFORM/$execname $*
