#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:41:59 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME = 	../..

SOURCES = 	\
		u_cmd.cc \
		u_config.cc \
		u_date.cc \
		u_desc.cc \
		u_env.cc \
		u_file.cc \
		u_file_rd.cc \
		u_fopen.cc \
		u_id.cc \
		u_keyword.cc \
		u_log.cc \
		u_mc_dbms.cc \
		u_print.cc \
		u_string.cc \
		u_trace.cc \
		u_tspec.cc \
		u_udmenu.cc \
		u_udmenu_rd.cc \
		u_userid.cc
		#u_ptrep.cc \
		u_repdata.cc \

C_SOURCES =	

COMPONENT = UTIL

LIBNAME =	lib$(COMPONENT).a

SCHEMA_SOURCE =	u_schema

SCHEMA_LIB =	libUTIL.ldb

include		${SOURCE_HOME}/make/leaf.mk

