#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:43:10 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME =	../../..

SOURCES = \
		main_gen_erate.cc \

COMPONENT = GENERATOR

LIBNAME =	libM$(COMPONENT).a

# APPL_SCHEMAS is a list of file name suffices.  For each one,
# the is a source file named schemxxx.cc which will generate
# and ldb file names libxxx.ldb.  Limit xxx to three characters
# to stay within the 8-character file name constraint.

APPL_SCHEMAS = 

include		${SOURCE_HOME}/make/leaf.mk

