# makefile for make-based platforms

ALL_TARGETS =  opttest$(E) listtest$(E) notebk$(E)

!include ..\environ

LDLIBS_HOOK =

opttestOBJS = opttest$(O)

LDLIBS_HOOK =

listtestOBJS = listtest$(O)

LDLIBS_HOOK =

notebkOBJS = notebk$(O)

