# makefile for make-based platforms

ALL_TARGETS =  fontchsr$(E) fontchs2$(E)

!include ..\environ

LDLIBS_HOOK =

fontchsrOBJS = fontchsr$(O)

LDLIBS_HOOK =

fontchs2OBJS = fontchs2$(O)

