# makefile for make-based platforms

ALL_TARGETS =  pc$(E) pc2$(E) worker$(E)

!include ..\environ

LDLIBS_HOOK =

pcOBJS = pc$(O)

LDLIBS_HOOK =

pc2OBJS = pc2$(O)

LDLIBS_HOOK =

workerOBJS = worker$(O)

