/* $Id: calc.c,v 1.8 1996/03/22 21:49:54 stevek Exp $
 *
 * The following Sample Code is provided for your reference purposes in
 * connection with your use of the Galaxy Application Environment (TM) software
 * product which you have licensed from Visix Software, Inc. ("Visix").
 * The Sample code is provided to you without any warranty of any kind
 * whatsoever and you agree to be responsible for the use and/or incorporation
 * of the Sample Code into any software product you develop. You agree to fully
 * and completely indemnify and hold Visix harmless from any and all loss,
 * claim, liability or damages with respect to your use of the Sample Code.  
 *
 * Subject to the foregoing, you are permitted to copy, modify, and distribute
 * the Sample Code for any purpose and without fee, provided that (i) a
 * copyright notice in the in the form of "Copyright 1992,93 Visix Software
 * Inc., 11440 Commerce Park Drive, Reston, VA  22091. All Rights Reserved"
 * appears in all copies, (ii) both the copyright notice and this permission
 * notice appear in supporting documentation and (iii) you are a valid
 * licensee of Galaxy Application Environment.
 */

/****************************************************************************
 * executable:    calc
 * .c files:      calc.c
 * header file:   gen.h
 * resource file: calc.vr
 *
 * Two-button calculator example.
 *
 * This program illustrates how to load a simple dialog from a resource file
 * and how to use notify functions to associate application code with user 
 * interface items. It illustrates how to retrieve typed-in user input via
 * textitem GUI objects. It also illustrates how to use code that vre can
 * generate automatically to refer to all user interface items by
 * constant internal names.
 *
 * This demo consists of a single dialog which is a two-button calculator
 * that adds and multiplies integers.
 *
 * To end the demo, Quit the dialog using your window manager menu.
 *
 ****************************************************************************/


#ifndef vportINCLUDED		/* for v*HEADER */
#include <vport.h>
#endif

#ifndef  vstdlibINCLUDED	/* for EXIT_SUCCESS */
#include vstdlibHEADER
#endif

#include vnameHEADER
#include veventHEADER
#include vresourceHEADER
#include vnumHEADER
#include vapplicationHEADER
#include vdialogHEADER
#include vbuttonHEADER
#include vtextitemHEADER
#include vstartupHEADER
#include vtestHEADER

#include "gen.h"  /* the header file that was generated by vre */


/* forward references */
static void shutdownMain (void);
static void dialogNoteProc (vdialog *dialog, vevent *event);
static void multButtonNoteProc (vbutton *button, vevent *event);
static void addButtonNoteProc (vbutton *button, vevent *event);


/* Constants (generated by vre) */

const vname	 *_generatedPredefs[_generatedCOUNT];
static const char	 *_generated_predefStrings[] = {
	"CALC_ADD_BUTTON",
	"CALC_RESULT_LABEL",
	"CALC_OP1_LABEL",
	"CALC_MULT_BUTTON",
	"CALC_OP1",
	"CALC_OP2",
	"CALC_RESULT",
	"Dialog",
	"CALC_OP2_LABEL"
};

/* Note - this function, generatedInternNames(), was generated by vre */
void generatedInternNames() 
{
	register int	i;

	for ( i = 0; i < _generatedCOUNT; i++ ) 
		_generatedPredefs[i] = vnameInternGlobalLiteral( _generated_predefStrings[i] );
}


/*********
 * main()
 *
 * The main program for our simpleCalc example.
 *
 **********/
int main (int argc, char *argv[])
{
  vdialog     *dialog;
  vbutton     *button;
  vresource    resource;

  /* Initialize Galaxy */
  vstartup (argc, argv);

  /* Connect to any running testing tools */
  vtestStartup();

  /* call the function generated by vre to intern all dialog item tags */
  generatedInternNames();

  /*
   * Load the dialog from the application resource file.
   */

  resource = vresourceGet (vapplicationGetResources (vapplicationGetCurrent()),
			   generated_Dialog);
  dialog = vdialogLoad (resource);
  vdialogSetNotify (dialog, dialogNoteProc);

  /*
   * Find the buttons and attach their notifies.
   */

  button = (vbutton *) vdialogFindItem (dialog, generated_CALC_MULT_BUTTON);
  vbuttonSetNotify (button, multButtonNoteProc);
  
  button = (vbutton *) vdialogFindItem (dialog, generated_CALC_ADD_BUTTON);
  vbuttonSetNotify (button, addButtonNoteProc);
  
  /* Open the dialog */
  vwindowPlace(vdialogGetWindow(dialog), vwindowGetRoot(), 
	       vrectPLACE_CENTER, vrectPLACE_CENTER);
  vdialogOpen (dialog);

  /* Enter the event loop */
  veventProcess ();

  /* Return the dialog's resources to the system */
  vdialogDestroy (dialog);

  exit (EXIT_SUCCESS);
  return EXIT_FAILURE;

}


/*********
 *  shutdownMain()
 *
 *  Stop things.
 *
 **********/
static void shutdownMain()
{

  veventStopProcessing();

}


/*********
 *  dialogNoteProc()
 *
 *  The dialog notification procedure gets called whenever any 
 *  major event applies to the dialog as a whole.  We need to
 *  look for the event which tells us that the dialog has
 *  closed.
 *
 **********/
static void dialogNoteProc (vdialog *dialog, vevent *event)
{
  int      et;

  et = veventGetType (event);
  
  if (et == veventWINDOW_STATE && veventIsClose (event))
    shutdownMain ();

}


/*********
 *  multButtonNoteProc
 *
 *  This button notification procedure gets called whenever the user
 *  presses the Multiply button. Do the multiplication and put the 
 *  product in the visual result box.
 *
 **********/
static void multButtonNoteProc (vbutton *button, vevent *event)
{
  vdialog   *dialog;
  int        volatile op1;
  int        volatile op2;
  int        theResult;
  vtextitem *op1TextItem, *op2TextItem, *resultItem;
  vscribe   *volatile resultAsScribe;
  vbool      volatile errorOccurred = FALSE;

  dialog =  vdialogDetermineItemDialog (vbuttonGetItem (button));
  op1TextItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_OP1);
  op2TextItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_OP2);
  resultItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_RESULT);

  vexWITH_HANDLING {
    op1 = vtextitemGetTextAsInt(op1TextItem);
    op2 = vtextitemGetTextAsInt(op2TextItem);
  }
  vexON_EXCEPTION {
    if (vnumGetSyntaxException() != NULL )
      {
	resultAsScribe = vcharScribeLiteral("Non-integer Operand(s) !");
	errorOccurred = TRUE;
      }
    if (vnumGetRangeException() != NULL )
      {
	resultAsScribe = vcharScribeLiteral("Operand(s) Out Of Range !");
	errorOccurred = TRUE;
      }

  } vexEND_HANDLING;

  if (!errorOccurred)
    {
      theResult = op1 * op2;
      resultAsScribe = vnumScribeInt(theResult);
    }

  vtextitemSetTextScribed(resultItem, resultAsScribe);
}


/*********
 *  addButtonNoteProc()
 *
 *  This button notification procedure gets called whenever the user
 *  presses the Add button. Do the addition and put the 
 *  sum in the visual result box.
 *
 **********/
static void addButtonNoteProc (vbutton *button, vevent *event)
{
  vdialog   *dialog;
  int        volatile op1;
  int        volatile op2;
  int        theResult;
  vtextitem *op1TextItem, *op2TextItem, *resultItem;
  vscribe   *volatile resultAsScribe;
  vbool      volatile errorOccurred = FALSE;

  dialog =  vdialogDetermineItemDialog (vbuttonGetItem (button));
  op1TextItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_OP1);
  op2TextItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_OP2);
  resultItem = (vtextitem *)vdialogFindItem(dialog, generated_CALC_RESULT);

  vexWITH_HANDLING {
    op1 = vtextitemGetTextAsInt(op1TextItem);
    op2 = vtextitemGetTextAsInt(op2TextItem);
  }
  vexON_EXCEPTION {
    if (vnumGetSyntaxException() != NULL )
      {
	resultAsScribe = vcharScribeLiteral("Non-integer Operand(s) !");
	errorOccurred = TRUE;
      }
    if (vnumGetRangeException() != NULL )
      {
	resultAsScribe = vcharScribeLiteral("Operand(s) Out Of Range !");
	errorOccurred = TRUE;
      }
  } vexEND_HANDLING;

  if (!errorOccurred)
    {
      theResult = op1 + op2;
      resultAsScribe = vnumScribeInt(theResult);
    }

  vtextitemSetTextScribed(resultItem, resultAsScribe);
}

