#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.9 $
# Modified:  $Date: 2013/01/10 23:42:36 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME =	../..

SOURCES =	\
		a_bush.cc \
		a_gfinds.cc

COMPONENT = AL

LIBNAME =	lib$(COMPONENT).a

include		${SOURCE_HOME}/make/leaf.mk

