/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_odi_consulting_Monitor */

#ifndef _Included_com_odi_consulting_Monitor
#define _Included_com_odi_consulting_Monitor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _initialized */
/*
 * Class:     com_odi_consulting_Monitor
 * Method:    _initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_odi_consulting_Monitor__1initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_odi_consulting_Monitor
 * Method:    _initializeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_odi_consulting_Monitor__1initializeAll
  (JNIEnv *, jclass);

/*
 * Class:     com_odi_consulting_Monitor
 * Method:    _log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_odi_consulting_Monitor__1log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
