# makefile for make-based platforms

ALL_TARGETS =  toolbar1$(E) toolbar2$(E)

!include ..\environ

LDLIBS_HOOK =

toolbar1OBJS = toolbar1$(O)

LDLIBS_HOOK =

toolbar2OBJS = toolbar2$(O)

