#==========================================================================
#
# File:      $RCSfile: makefile,v $
# Version:   $Revision: 1.10 $
# Modified:  $Date: 2013/01/10 23:41:36 $
#
# (c) Copyright 1992-2013 by Mentor Graphics Corp. All rights reserved.
#
#==========================================================================
# This document contains information proprietary and confidential to
# Mentor Graphics Corp., and is not for external distribution.
#==========================================================================
#

SOURCE_HOME = ../../..

SOURCES	= \
		i_ainst.cc \
		i_attr.cc \
		i_c_rop.cc \
		i_clock.cc \
		i_einst.cc \
		i_esdi.cc \
		i_esdii.cc \
		i_evt.cc \
		i_idaref.cc \
		i_idb.cc \
		i_ir_rop.cc \
		i_obj.cc \
		i_oinst.cc \
		i_rel.cc \
		i_relate.cc \
		i_roip.cc \
		i_rop.cc \
		i_var.cc \
		schema_gen.cc \
		mcdbms_restore.cc

COMPONENT = GS_IDB

LIBNAME =	lib$(COMPONENT).a

include		${SOURCE_HOME}/make/leaf.mk

